import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  getStartedSidebar: [{type: 'autogenerated', dirName: 'get-started'}],
  mobileSidebar: [{type: 'autogenerated', dirName: 'mobile'}],
  backofficeSidebar: [{type: 'autogenerated', dirName: 'backoffice'}],
};

export default sidebars;
